### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by khirakawa** [ember-cli/broccoli-concat#59]
The documentation reads:

```
The structure of output.js will be as follows:

// - header
// - ordered content of the files in headerFiles
// - un-ordered content of files matched by inputFiles, but not in headerFiles or footerFiles
// - ordered content of the files in footerFiles
// - footer
```

Does this mean that if I have:
```
inputFiles: ['fileA', 'fileB']
```

The order of fileA and fileB in the final outputted file is not guaranteed? If so, how can I guarantee the order is as specified in the inputFiles array?

**Comment by stefanpenner** [comment]
Sorry for letting this linger:

* `inputFiles` order in 2.x is not guaranteed, if a guarantee is required please use `headerFiles` or `footerFiles` which are preserve exact order
* `inputFiles` order in 3.x is guaranteed to be lexicographical 

Why is this the case?

* `inputFiles` allows for an array of globs and non-glob inputs, which makes an order guarantee much more complicated (although not impossible) to implement, I believe though it will be hard to reason about order when considering specificity of several complex globs. Because of this, `inputFiles` should be considered not order preserving, but as of 3.x the files matched by inputFiles will be lexicographically sorted based on their relativePath. Which should help with build/outputfile stability.
